<%@ tag body-content="scriptless" import="
	java.util.Map,
	java.util.HashMap,
	java.util.ArrayList,
	java.util.Date,
	java.util.Locale,
	java.util.TimeZone,
	java.lang.StringBuffer,
	java.util.*,
	java.lang.Integer,
	java.text.*,
	java.util.Collection,
	java.util.Calendar,
	java.text.DateFormat,
	java.text.SimpleDateFormat,
	java.util.Locale,
	com.eidosmedia.portal.util.*"
	trimDirectiveWhitespaces="true"	
%>

<%@ taglib prefix="p" uri="ptag"%>
<%@ taglib prefix="c" uri="jstlCore"%>
<%@ taglib prefix="fn" uri="jstlFunctions"%>
<%@ taglib prefix="fmt" uri="formatTags" %>
<%@ taglib prefix="x" uri="jstlXml" %>
<%@ include file="bdc.inc" %>
